/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkinn.view;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ACEWR
 */
public class BookingHistoryView extends javax.swing.JFrame {

    /**
     * Creates new form BookingHistoryView
     */
    public BookingHistoryView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Booking History | CheckInn");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        RedirectToDashboardButton = new javax.swing.JButton();
        BookingHistoryButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        UserProfile = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        UserProfileRedirectionButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CheckInnLogo = new javax.swing.JLabel();
        BoyWithStuffImg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SingleRoomViewInvoice = new javax.swing.JButton();
        SingleLabel = new javax.swing.JLabel();
        CheckOutLabelSingle = new javax.swing.JLabel();
        CheckInLabelSingle = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        DoubleRoomViewInvoice = new javax.swing.JButton();
        DoubleLabel = new javax.swing.JLabel();
        CheckOutLabelDouble = new javax.swing.JLabel();
        CheckInLabelDouble = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ExecutiveSuiteVieWInvoice = new javax.swing.JButton();
        ExecutiveSuiteLabel = new javax.swing.JLabel();
        CheckInLabelExecutiveSuite = new javax.swing.JLabel();
        CheckOutLabelExecutiveSuite = new javax.swing.JLabel();
        AccomodationLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        CheckInLabel = new javax.swing.JLabel();
        CheckOutLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        DeluxeRoomViewInvoice = new javax.swing.JButton();
        DeluxeLabel = new javax.swing.JLabel();
        CheckInLabelDeluxe = new javax.swing.JLabel();
        CheckOutLabelDeluxe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(23, 194, 157));

        RedirectToDashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RedirectToDashboardButton.setText("Dashboard");
        RedirectToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedirectToDashboardButtonActionPerformed(evt);
            }
        });

        BookingHistoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookingHistoryButton.setText("Booking history");
        BookingHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingHistoryButtonActionPerformed(evt);
            }
        });

        LogOutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7124045_logout_icon(1).png"))); // NOI18N
        LogOutButton.setText("Logout");

        UserProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-3296(2).png"))); // NOI18N
        UserProfile.setText("jLabel11");

        UserNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserNameLabel.setText("sukrant kharel");

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dsh2.png"))); // NOI18N

        UserProfileRedirectionButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserProfileRedirectionButton.setText("Profile");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogOutButton)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(RedirectToDashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BookingHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UserProfileRedirectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(UserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Image)
                .addGap(77, 77, 77))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserProfile)
                    .addComponent(UserNameLabel))
                .addGap(52, 52, 52)
                .addComponent(RedirectToDashboardButton)
                .addGap(27, 27, 27)
                .addComponent(BookingHistoryButton)
                .addGap(33, 33, 33)
                .addComponent(UserProfileRedirectionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Image)
                .addGap(62, 62, 62)
                .addComponent(LogOutButton)
                .addGap(48, 48, 48))
        );

        jPanel2.setBackground(new java.awt.Color(23, 194, 157));

        CheckInnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkinnlogo.png"))); // NOI18N

        BoyWithStuffImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BoyWithStuff.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(CheckInnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 838, Short.MAX_VALUE)
                .addComponent(BoyWithStuffImg)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BoyWithStuffImg)
                    .addComponent(CheckInnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(23, 194, 157));

        SingleRoomViewInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SingleRoomViewInvoice.setText("View Invoice");
        SingleRoomViewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleRoomViewInvoiceActionPerformed(evt);
            }
        });

        SingleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SingleLabel.setText("Single");

        CheckOutLabelSingle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckOutLabelSingle.setText("xx-xx-xxxx");

        CheckInLabelSingle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckInLabelSingle.setText("xx-xx-xxxx");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(SingleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CheckInLabelSingle)
                .addGap(171, 171, 171)
                .addComponent(CheckOutLabelSingle)
                .addGap(142, 142, 142)
                .addComponent(SingleRoomViewInvoice)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SingleLabel)
                        .addComponent(CheckOutLabelSingle)
                        .addComponent(CheckInLabelSingle))
                    .addComponent(SingleRoomViewInvoice))
                .addGap(19, 19, 19))
        );

        jPanel6.setBackground(new java.awt.Color(23, 194, 157));

        DoubleRoomViewInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoubleRoomViewInvoice.setText("View Invoice");
        DoubleRoomViewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleRoomViewInvoiceActionPerformed(evt);
            }
        });

        DoubleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoubleLabel.setText("Double");

        CheckOutLabelDouble.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckOutLabelDouble.setText("xx-xx-xxxx");

        CheckInLabelDouble.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckInLabelDouble.setText("xx-xx-xxxx");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(DoubleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CheckInLabelDouble)
                .addGap(174, 174, 174)
                .addComponent(CheckOutLabelDouble)
                .addGap(146, 146, 146)
                .addComponent(DoubleRoomViewInvoice)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoubleRoomViewInvoice)
                    .addComponent(DoubleLabel)
                    .addComponent(CheckOutLabelDouble)
                    .addComponent(CheckInLabelDouble))
                .addGap(18, 18, 18))
        );

        jPanel4.setBackground(new java.awt.Color(23, 194, 157));

        ExecutiveSuiteVieWInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExecutiveSuiteVieWInvoice.setText("View Invoice");
        ExecutiveSuiteVieWInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutiveSuiteVieWInvoiceActionPerformed(evt);
            }
        });

        ExecutiveSuiteLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExecutiveSuiteLabel.setText("Executive Suite");

        CheckInLabelExecutiveSuite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckInLabelExecutiveSuite.setText("xx-xx-xxxx");

        CheckOutLabelExecutiveSuite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckOutLabelExecutiveSuite.setText("xx-xx-xxxx");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(ExecutiveSuiteLabel)
                .addGap(161, 161, 161)
                .addComponent(CheckInLabelExecutiveSuite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(CheckOutLabelExecutiveSuite)
                .addGap(148, 148, 148)
                .addComponent(ExecutiveSuiteVieWInvoice)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExecutiveSuiteVieWInvoice)
                    .addComponent(ExecutiveSuiteLabel)
                    .addComponent(CheckInLabelExecutiveSuite)
                    .addComponent(CheckOutLabelExecutiveSuite))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        AccomodationLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccomodationLabel.setText("Accomodation");

        TitleLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        TitleLabel.setText("BOOKING HISTORY");

        CheckInLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckInLabel.setText("Check-in");

        CheckOutLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckOutLabel.setText("Check-out");

        jPanel5.setBackground(new java.awt.Color(23, 194, 157));

        DeluxeRoomViewInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeluxeRoomViewInvoice.setText("View Invoice");
        DeluxeRoomViewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeluxeRoomViewInvoiceActionPerformed(evt);
            }
        });

        DeluxeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeluxeLabel.setText("Deluxe");

        CheckInLabelDeluxe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckInLabelDeluxe.setText("xx-xx-xxxx");

        CheckOutLabelDeluxe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckOutLabelDeluxe.setText("xx-xx-xxxx");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(DeluxeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CheckInLabelDeluxe)
                .addGap(175, 175, 175)
                .addComponent(CheckOutLabelDeluxe)
                .addGap(150, 150, 150)
                .addComponent(DeluxeRoomViewInvoice)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeluxeRoomViewInvoice)
                    .addComponent(DeluxeLabel)
                    .addComponent(CheckInLabelDeluxe)
                    .addComponent(CheckOutLabelDeluxe))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(AccomodationLabel)
                                .addGap(174, 174, 174)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CheckInLabel)
                                        .addGap(185, 185, 185)
                                        .addComponent(CheckOutLabel))
                                    .addComponent(TitleLabel))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccomodationLabel)
                            .addComponent(CheckInLabel)
                            .addComponent(CheckOutLabel))
                        .addGap(56, 56, 56)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RedirectToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedirectToDashboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RedirectToDashboardButtonActionPerformed

    private void BookingHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingHistoryButtonActionPerformed

    private void SingleRoomViewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleRoomViewInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SingleRoomViewInvoiceActionPerformed

    private void DoubleRoomViewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleRoomViewInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleRoomViewInvoiceActionPerformed

    private void ExecutiveSuiteVieWInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutiveSuiteVieWInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExecutiveSuiteVieWInvoiceActionPerformed

    private void DeluxeRoomViewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeluxeRoomViewInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeluxeRoomViewInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingHistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingHistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingHistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingHistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BookingHistoryView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccomodationLabel;
    private javax.swing.JButton BookingHistoryButton;
    private javax.swing.JLabel BoyWithStuffImg;
    private javax.swing.JLabel CheckInLabel;
    private javax.swing.JLabel CheckInLabelDeluxe;
    private javax.swing.JLabel CheckInLabelDouble;
    private javax.swing.JLabel CheckInLabelExecutiveSuite;
    private javax.swing.JLabel CheckInLabelSingle;
    private javax.swing.JLabel CheckInnLogo;
    private javax.swing.JLabel CheckOutLabel;
    private javax.swing.JLabel CheckOutLabelDeluxe;
    private javax.swing.JLabel CheckOutLabelDouble;
    private javax.swing.JLabel CheckOutLabelExecutiveSuite;
    private javax.swing.JLabel CheckOutLabelSingle;
    private javax.swing.JLabel DeluxeLabel;
    private javax.swing.JButton DeluxeRoomViewInvoice;
    private javax.swing.JLabel DoubleLabel;
    private javax.swing.JButton DoubleRoomViewInvoice;
    private javax.swing.JLabel ExecutiveSuiteLabel;
    private javax.swing.JButton ExecutiveSuiteVieWInvoice;
    private javax.swing.JLabel Image;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton RedirectToDashboardButton;
    private javax.swing.JLabel SingleLabel;
    private javax.swing.JButton SingleRoomViewInvoice;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JLabel UserProfile;
    private javax.swing.JButton UserProfileRedirectionButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

public void addBackToDashboardListener(java.awt.event.ActionListener listener) {
    RedirectToDashboardButton.addActionListener(listener); 
}

public void addUserProfileRedirectionListener(java.awt.event.ActionListener listener) {
    UserProfileRedirectionButton.addActionListener(listener);
}

public void addLogoutListener(java.awt.event.ActionListener listener) {
    LogOutButton.addActionListener(listener);
}

        public void addBookingHistoryListener(java.awt.event.ActionListener listener) {
    BookingHistoryButton.addActionListener(listener);
}

public void setUserNameLabel(String name) {
    UserNameLabel.setText(name);
}

public void setRoomPanelData(int roomId, Date checkIn, Date checkOut, boolean enableInvoiceButton) {
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    switch (roomId) {
        case 1:
            CheckInLabelSingle.setText(checkIn != null ? sdf.format(checkIn) : "-");
            CheckOutLabelSingle.setText(checkOut != null ? sdf.format(checkOut) : "-");
            SingleRoomViewInvoice.setEnabled(enableInvoiceButton);
            break;
        case 2:
            CheckInLabelDouble.setText(checkIn != null ? sdf.format(checkIn) : "-");
            CheckOutLabelDouble.setText(checkOut != null ? sdf.format(checkOut) : "-");
            DoubleRoomViewInvoice.setEnabled(enableInvoiceButton);
            break;
        case 3:
            CheckInLabelDeluxe.setText(checkIn != null ? sdf.format(checkIn) : "-");
            CheckOutLabelDeluxe.setText(checkOut != null ? sdf.format(checkOut) : "-");
            DeluxeRoomViewInvoice.setEnabled(enableInvoiceButton);
            break;
        case 4:
            CheckInLabelExecutiveSuite.setText(checkIn != null ? sdf.format(checkIn) : "-");
            CheckOutLabelExecutiveSuite.setText(checkOut != null ? sdf.format(checkOut) : "-");
            ExecutiveSuiteVieWInvoice.setEnabled(enableInvoiceButton);
            break;
    }
}

public void addRoomInvoiceButtonListener(int roomId, java.awt.event.ActionListener listener) {
    switch (roomId) {
        case 1: SingleRoomViewInvoice.addActionListener(listener); break;
        case 2: DoubleRoomViewInvoice.addActionListener(listener); break;
        case 3: DeluxeRoomViewInvoice.addActionListener(listener); break;
        case 4: ExecutiveSuiteVieWInvoice.addActionListener(listener); break;
    }
}

public Date getCheckInDateForRoom(int roomId) {
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        switch (roomId) {
            case 1: return sdf.parse(CheckInLabelSingle.getText());
            case 2: return sdf.parse(CheckInLabelDouble.getText());
            case 3: return sdf.parse(CheckInLabelDeluxe.getText());
            case 4: return sdf.parse(CheckInLabelExecutiveSuite.getText());
        }
    } catch (Exception e) {
        return null;
    }
    return null;
}

public Date getCheckOutDateForRoom(int roomId) {
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        switch (roomId) {
            case 1: return sdf.parse(CheckOutLabelSingle.getText());
            case 2: return sdf.parse(CheckOutLabelDouble.getText());
            case 3: return sdf.parse(CheckOutLabelDeluxe.getText());
            case 4: return sdf.parse(CheckOutLabelExecutiveSuite.getText());
        }
    } catch (Exception e) {
        return null;
    }
    return null;
}

}
