/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkinn.view;

/**
 *
 * @author risha
 */
public class InvoiceView extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceView
     */
    public InvoiceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        InvoicePanel = new javax.swing.JPanel();
        LogoLabel = new javax.swing.JLabel();
        TopicLabel = new javax.swing.JLabel();
        RoomTypeField = new javax.swing.JLabel();
        CheckInDateField = new javax.swing.JLabel();
        InvoiceCheckIn = new javax.swing.JLabel();
        CheckOutDateField = new javax.swing.JLabel();
        InvoiceCheckOut = new javax.swing.JLabel();
        MenuItemsField = new javax.swing.JLabel();
        InvoiceMenuItems = new javax.swing.JLabel();
        InvoiceRoomName = new javax.swing.JLabel();
        TotalPriceField = new javax.swing.JLabel();
        InvoiceTotalPrice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvoicePanel.setBackground(new java.awt.Color(255, 255, 204));
        InvoicePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkinnlogo.png"))); // NOI18N
        LogoLabel.setText("jLabel2");

        TopicLabel.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        TopicLabel.setText("Invoice");

        RoomTypeField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        RoomTypeField.setText("Room Type : ");

        CheckInDateField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CheckInDateField.setText("Check-In Date :");

        InvoiceCheckIn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        InvoiceCheckIn.setText("XX-XX-XXXX");

        CheckOutDateField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CheckOutDateField.setText("Check-Out Date :");

        InvoiceCheckOut.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        InvoiceCheckOut.setText("XX-XX-XXXX");

        MenuItemsField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        MenuItemsField.setText("Menu Items :");

        InvoiceMenuItems.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        InvoiceMenuItems.setText("Breakfast, Brunch, Lunch, Dinner");

        InvoiceRoomName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        InvoiceRoomName.setText("<RoomName>");

        TotalPriceField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TotalPriceField.setText("Total Price : ");

        InvoiceTotalPrice.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        InvoiceTotalPrice.setText("Rs. XX.XX");

        javax.swing.GroupLayout InvoicePanelLayout = new javax.swing.GroupLayout(InvoicePanel);
        InvoicePanel.setLayout(InvoicePanelLayout);
        InvoicePanelLayout.setHorizontalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelLayout.createSequentialGroup()
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TopicLabel)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InvoicePanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InvoicePanelLayout.createSequentialGroup()
                                .addComponent(CheckInDateField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InvoiceCheckIn))
                            .addGroup(InvoicePanelLayout.createSequentialGroup()
                                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckOutDateField)
                                    .addComponent(MenuItemsField)
                                    .addComponent(RoomTypeField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InvoiceCheckOut, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(InvoiceMenuItems, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(InvoiceRoomName, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(49, 49, 49))
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TotalPriceField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InvoiceTotalPrice)
                .addGap(43, 43, 43))
        );
        InvoicePanelLayout.setVerticalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogoLabel)
                    .addComponent(TopicLabel))
                .addGap(54, 54, 54)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomTypeField)
                    .addComponent(InvoiceRoomName))
                .addGap(70, 70, 70)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInDateField)
                    .addComponent(InvoiceCheckIn))
                .addGap(80, 80, 80)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutDateField)
                    .addComponent(InvoiceCheckOut))
                .addGap(87, 87, 87)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuItemsField)
                    .addComponent(InvoiceMenuItems))
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPriceField)
                    .addComponent(InvoiceTotalPrice))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InvoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InvoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CheckInDateField;
    private javax.swing.JLabel CheckOutDateField;
    private javax.swing.JLabel InvoiceCheckIn;
    private javax.swing.JLabel InvoiceCheckOut;
    private javax.swing.JLabel InvoiceMenuItems;
    private javax.swing.JPanel InvoicePanel;
    private javax.swing.JLabel InvoiceRoomName;
    private javax.swing.JLabel InvoiceTotalPrice;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel MenuItemsField;
    private javax.swing.JLabel RoomTypeField;
    private javax.swing.JLabel TopicLabel;
    private javax.swing.JLabel TotalPriceField;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
