/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkinn.view;

import checkinn.model.UserData;

/**
 *
 * @author ACER NITRO
 */
public class UserProfileView extends javax.swing.JFrame {
private Object parentController;
    /**
     * Creates new form UserProfile
     */
    public UserProfileView(UserData user) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserProfilePannel = new javax.swing.JPanel();
        ImageLabel = new javax.swing.JLabel();
        UserProfile = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JTextField();
        BackToDashboard = new javax.swing.JButton();
        DeleteAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dsh.png"))); // NOI18N

        UserProfile.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UserProfile.setText("USER PROFILE");

        Username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username.setText("Full Name");

        PhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhoneNumber.setText("Phone Number");

        BackToDashboard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BackToDashboard.setText("<- Dashboard");

        DeleteAccountButton.setBackground(new java.awt.Color(255, 0, 0));
        DeleteAccountButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DeleteAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteAccountButton.setText("Delete Account");

        javax.swing.GroupLayout UserProfilePannelLayout = new javax.swing.GroupLayout(UserProfilePannel);
        UserProfilePannel.setLayout(UserProfilePannelLayout);
        UserProfilePannelLayout.setHorizontalGroup(
            UserProfilePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserProfilePannelLayout.createSequentialGroup()
                .addGroup(UserProfilePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserProfilePannelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(UserProfilePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PhoneNumber)
                            .addComponent(Username))
                        .addGap(128, 128, 128)
                        .addGroup(UserProfilePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameLabel)
                            .addComponent(PhoneNumberLabel)))
                    .addGroup(UserProfilePannelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(UserProfile)))
                .addGap(46, 46, 46))
            .addGroup(UserProfilePannelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(DeleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserProfilePannelLayout.setVerticalGroup(
            UserProfilePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserProfilePannelLayout.createSequentialGroup()
                .addGroup(UserProfilePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserProfilePannelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserProfilePannelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(UserProfile))
                    .addGroup(UserProfilePannelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(BackToDashboard)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(UserProfilePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(UserProfilePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addComponent(DeleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserProfilePannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserProfilePannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserData user = null;
                new UserProfileView(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToDashboard;
    private javax.swing.JButton DeleteAccountButton;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JTextField PhoneNumberLabel;
    private javax.swing.JTextField UserNameLabel;
    private javax.swing.JLabel UserProfile;
    private javax.swing.JPanel UserProfilePannel;
    private javax.swing.JLabel Username;
    // End of variables declaration//GEN-END:variables
public void addBackToDashboardListener(java.awt.event.ActionListener listener) {
    BackToDashboard.addActionListener(listener);
}


public void addDeleteAccountListener(java.awt.event.ActionListener listener){
    DeleteAccountButton.addActionListener(listener);  
        }

public void setUserProfileData(String fullName, String phoneNumber) {
    UserNameLabel.setText(fullName);
    PhoneNumberLabel.setText(phoneNumber);
}

public void setParentController(Object parentController) {
    this.parentController = parentController;
}

}


